# Generated by Django 4.1 on 2022-08-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('adventure', models.CharField(choices=[('beach', 'Beach'), ('diving', 'Diving'), ('city', 'City'), ('hiking', 'Hiking')], max_length=20, verbose_name='Adventure')),
                ('climate', models.CharField(choices=[('tropical', 'Tropical'), ('cold', 'Cold'), ('temperate', 'Temperate')], max_length=50, verbose_name='Climate')),
                ('flight', models.CharField(choices=[('short', 'Short'), ('long', 'Long')], max_length=50, verbose_name='Flight Length')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('adventure', models.CharField(choices=[('beach', 'Beach'), ('diving', 'Diving'), ('city', 'City'), ('hiking', 'Hiking')], max_length=20, verbose_name='Adventure')),
                ('climate', models.CharField(choices=[('tropical', 'Tropical'), ('cold', 'Cold'), ('temperate', 'Temperate')], max_length=50, verbose_name='Climate')),
                ('flight', models.CharField(choices=[('short', 'Short'), ('long', 'Long')], max_length=50, verbose_name='Flight Length')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Next',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventure', models.CharField(choices=[('beach', 'Beach'), ('diving', 'Diving'), ('city', 'City'), ('hiking', 'Hiking')], max_length=20, verbose_name='Type of Adventure')),
                ('climate', models.CharField(choices=[('tropical', 'Tropical'), ('cold', 'Cold'), ('temperate', 'Temperate')], max_length=50, verbose_name='Climate')),
                ('flight', models.CharField(choices=[('short', 'Short'), ('long', 'Long')], max_length=50, verbose_name='Flight Length')),
            ],
        ),
    ]
